plugins:
  qa_tags:
    client: true
    type: list
    default: 'question'
  qa_show_topic_tip:
    client: true
    default: true
  qa_enabled:
    client: true
    default: true
  qa_disable_like_on_answers:
    client: true
    default: false
  qa_undo_vote_action_window:
    default: 10
  qa_comments_default:
    default: 3
    client: true
  qa_trust_level_vote_limits:
    default: false
    client: true
  qa_tl1_vote_limit:
    default: 1
    client: true
  qa_tl2_vote_limit:
    default: 2
    client: true
  qa_tl3_vote_limit:
    default: 3
    client: true
  qa_tl4_vote_limit:
    default: 4
    client: true
  qa_tl_allow_multiple_votes_per_post:
    default: false
    client: true
  qa_blacklist_tags:
    type: list
    default: ""
  qa_enabled_globally:
    default: false
    client: true
